server:
  port: 8081
  servlet:
    session:
      timeout: 1800s
spring:
  output:
    ansi:
      enabled: always #彩色日志
  #创建数据库 navivat选择字符集 utf8 排序规则：utf8_general_ci
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://101.132.71.171:3306/salary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      url: jdbc:mysql://localhost:3306/salary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
 #     password: ctgu@2017WH
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 101.132.71.171
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
#  jpa:
#    show-sql: true
#  redis:
#    jedis:
#      pool:
#        max-wait: 3000 #连接池最大阻塞等待时间
#        max-active: 100 #连接池最大连接数
#        max-idle: 20 #连接池中的最大空闲数
#        min-idle: 0 #连接池中的最小空闲数
#    timeout: 3000 #连接超时

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #实体类所做包
  type-aliases-package: com.ctgu.salary.po
  #mappers.xml所在位置
  mapper-locations: classpath:mappers/**/*.xml
logging:
  level:
    com:
      ctgu:
        salary:
          dao: debug
