server:
  port: 8081
  servlet:
    session:
      timeout: 1800s
spring:
  output:
    ansi:
      enabled: always #彩色日志
  #创建数据库 navivat选择字符集 utf8 排序规则：utf8_general_ci
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      #数据库访问配置
      url: jdbc:mysql://101.132.71.171:3306/salary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: ctgu@2017WH
      driver-class-name: com.mysql.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      #连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
#  redis:
#    jedis:
#      pool:
#        max-wait: 3000 #连接池最大阻塞等待时间
#        max-active: 100 #连接池最大连接数
#        max-idle: 20 #连接池中的最大空闲数
#        min-idle: 0 #连接池中的最小空闲数
#    timeout: 3000 #连接超时
mybatis:
  #实体类所做包
  type-aliases-package: com.ctgu.salary.po
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml